#! /bin/sh

set -e

case "$1" in
    configure|reconfigure)
	# add group immunity for the shadow users
	addgroup --system immunity
    ;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

