#!/bin/sh

unset PATH

INTERNET_USER=$(echo -n "$SUDO_USER" | /usr/bin/openssl dgst -md5)

if [ ! -d "/internet/$INTERNET_USER" ]; then
  /usr/sbin/useradd -b /internet -g internet -m -N -K UID_MIN=10000000 "$INTERNET_USER"
  /bin/chmod 700 "/internet/$INTERNET_USER"
fi

exit 0

