#! /bin/sh

set -e

case "$1" in
    configure|reconfigure)
	# add group internet for the shadow users
	addgroup --system internet
	if [ -x /etc/init.d/ipmasq ]; then
	    invoke-rc.d ipmasq restart
	fi
    ;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

